/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CNotOptionsJPanel.java
 *
 * Created on 2008-12-26, 14:10:36
 */

package jqcompgui;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Andrzej
 */
public class CNotOptionsJPanel extends javax.swing.JPanel {

    /** Creates new form CNotOptionsJPanel */
    public CNotOptionsJPanel() {
        initComponents();

        controlRowSpinner.setModel(new SpinnerNumberModel(0, 0, 100, 1));
        targetRowSpinner.setModel(new SpinnerNumberModel(0, 0, 100, 1));
    }
    
    public void setMaxRow(int maxRow) {
        this.maxRow = maxRow;
        ((SpinnerNumberModel)controlRowSpinner.getModel()).setMaximum(maxRow);
        ((SpinnerNumberModel)targetRowSpinner.getModel()).setMaximum(maxRow);
    }
    
    public int getMaxRow() {
        return maxRow;
    }

    public int getTargetRow() {
        return get(targetRowSpinner, "Target qubit is out of range");
    }

    public void setTargetRow(int qubit) {
        set(targetRowSpinner, qubit);
    }

    public int getControlRow() {
       return get(controlRowSpinner, "Control qubit is out of range");
    }

    public void setControlRow(int qubit) {
        set(controlRowSpinner, qubit);
    }

    private int get(JSpinner spn, String msg) {
        int qubit = (Integer)spn.getValue();
        if(!checkRow(qubit)) {
            JOptionPane.showMessageDialog(this, msg);
            return -1;
        }

        return qubit;
    }

    private void set(JSpinner spn, int qubit) {
        if(!checkRow(qubit)) {
            throw new RuntimeException("qubit");
        }

        spn.setValue(qubit);
    }

    private boolean checkRow(int qubit) {
        return qubit >= 0 && qubit <= maxRow;
    }

    private int maxRow = 0;



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        targetRowSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        controlRowSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Target qubit:");

        jLabel2.setText("Control qubit:");

        jLabel3.setText("Note: control and target qubits are relative to the insertion qubit above.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(controlRowSpinner)
                            .addComponent(targetRowSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(controlRowSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(targetRowSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner controlRowSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner targetRowSpinner;
    // End of variables declaration//GEN-END:variables

}
