/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HadamardOptionPanel.java
 *
 * Created on 2008-12-31, 20:07:25
 */

package jqcompgui;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Rafal
 */
public class HadamardOptionPanel extends javax.swing.JPanel {


    /** Creates new form HadamardOptionPanel */
    public HadamardOptionPanel() {
        initComponents();
     
    }

    

    public int getGateSize() {
        return (Integer)spn.getValue();
    }

    public void setGateSize(int gateSize) {
        spn.setValue(gateSize);
    }

    public void setMaxSize(int maxSize) {
           this.spn.setModel(new SpinnerNumberModel(1,1,maxSize,1));
    }
    
    



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spn = new javax.swing.JSpinner();

        jLabel1.setText("gate size:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner spn;
    // End of variables declaration//GEN-END:variables

}
