/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainJFrame.java
 *
 * Created on 2008-12-10, 00:57:38
 */
package jqcompgui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import pl.lodz.p.ics.quantum.jqcomp.QCircuit;
import pl.lodz.p.ics.quantum.jqcomp.qgates.CNot;
import pl.lodz.p.ics.quantum.jqcomp.qgates.CompoundQGate;
import pl.lodz.p.ics.quantum.jqcomp.qgates.ElementaryQGate;
import pl.lodz.p.ics.quantum.jqcomp.qgates.Hadamard;
import pl.lodz.p.ics.quantum.jqcomp.qgates.Identity;

/**
 *
 * @author rob
 */
public class MainJFrame extends javax.swing.JFrame {

    private static MainJFrame instance;

    public static MainJFrame getInstance() {
        if (instance == null) {
            instance = new MainJFrame();
        }
        return instance;
    }

    /** Creates new form MainJFrame */
    private MainJFrame() {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            /* DO NOTHING */
        }
        writeMsg("Quantum Computer Simulator started");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hadamardJButton = new javax.swing.JButton();
        notJButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        leftJPanel = new javax.swing.JPanel();
        resetJButton = new javax.swing.JButton();
        stepJButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        qCircuitJPanel = new jqcompgui.QCircuitJPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputJTextArea = new javax.swing.JTextArea();
        statusBarJPanel = new javax.swing.JPanel();
        statusBarJLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        newQuantumCircuitJMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        quitJMenuItem = new javax.swing.JMenuItem();
        quantumGatesJMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItem16 = new javax.swing.JMenuItem();
        algorithmsJMenu = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        entanglementAlgorithmJMenuItem = new javax.swing.JMenuItem();
        settingsJMenu = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        helpJMenu = new javax.swing.JMenu();
        helpContentsJMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jqcomp-gui: Java Quantum Computer Simulator. Technical University of Lodz");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        hadamardJButton.setText("Hadamard");
        jPanel2.add(hadamardJButton);

        notJButton.setText("Not");
        jPanel2.add(notJButton);

        jButton5.setText("CNot");
        jPanel2.add(jButton5);

        jButton6.setText("Phase");
        jPanel2.add(jButton6);

        jButton7.setText("Toffoli");
        jPanel2.add(jButton7);

        jButton8.setText("Custom");
        jPanel2.add(jButton8);

        leftJPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        resetJButton.setText("reset");
        resetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJButtonActionPerformed(evt);
            }
        });

        stepJButton.setText("step");
        stepJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepJButtonActionPerformed(evt);
            }
        });

        jButton2.setText("run");

        jButton9.setText("Forward");

        jButton10.setText("Backward");

        jButton11.setText("Remove");

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
            .addComponent(resetJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
            .addComponent(stepJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addComponent(resetJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.8);

        javax.swing.GroupLayout qCircuitJPanelLayout = new javax.swing.GroupLayout(qCircuitJPanel);
        qCircuitJPanel.setLayout(qCircuitJPanelLayout);
        qCircuitJPanelLayout.setHorizontalGroup(
            qCircuitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        qCircuitJPanelLayout.setVerticalGroup(
            qCircuitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(qCircuitJPanel);

        outputJTextArea.setColumns(20);
        outputJTextArea.setRows(5);
        jScrollPane1.setViewportView(outputJTextArea);

        jSplitPane1.setRightComponent(jScrollPane1);

        statusBarJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusBarJLabel.setText("status bar");

        javax.swing.GroupLayout statusBarJPanelLayout = new javax.swing.GroupLayout(statusBarJPanel);
        statusBarJPanel.setLayout(statusBarJPanelLayout);
        statusBarJPanelLayout.setHorizontalGroup(
            statusBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBarJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        statusBarJPanelLayout.setVerticalGroup(
            statusBarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBarJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        fileJMenu.setText("File");

        newQuantumCircuitJMenuItem.setText("New quantum circuit...");
        newQuantumCircuitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newQuantumCircuitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(newQuantumCircuitJMenuItem);

        jMenuItem3.setText("Load quantum circuit...");
        fileJMenu.add(jMenuItem3);

        jMenuItem2.setText("Save quantum circuit...");
        fileJMenu.add(jMenuItem2);
        fileJMenu.add(jSeparator3);

        quitJMenuItem.setText("Quit");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(quitJMenuItem);

        jMenuBar1.add(fileJMenu);

        quantumGatesJMenu.setText("Quantum Gates");

        jMenuItem4.setText("Hadamard");
        quantumGatesJMenu.add(jMenuItem4);

        jMenuItem9.setText("CNot");
        quantumGatesJMenu.add(jMenuItem9);

        jMenuItem8.setText("Not");
        quantumGatesJMenu.add(jMenuItem8);

        jMenuItem7.setText("Phase Shift");
        quantumGatesJMenu.add(jMenuItem7);

        jMenuItem6.setText("Toffoli");
        quantumGatesJMenu.add(jMenuItem6);

        jMenuItem5.setText("Fredkin");
        quantumGatesJMenu.add(jMenuItem5);
        quantumGatesJMenu.add(jSeparator2);

        jMenuItem16.setText("Custom quantum gate");
        quantumGatesJMenu.add(jMenuItem16);

        jMenuBar1.add(quantumGatesJMenu);

        algorithmsJMenu.setText("Algorithms");

        jMenuItem10.setText("Quantum teleportation");
        algorithmsJMenu.add(jMenuItem10);

        jMenuItem13.setText("Superdense coding");
        algorithmsJMenu.add(jMenuItem13);

        jMenuItem12.setText("Grover's fast search");
        algorithmsJMenu.add(jMenuItem12);

        entanglementAlgorithmJMenuItem.setText("Entangled states generation");
        entanglementAlgorithmJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entanglementAlgorithmJMenuItemActionPerformed(evt);
            }
        });
        algorithmsJMenu.add(entanglementAlgorithmJMenuItem);

        jMenuBar1.add(algorithmsJMenu);

        settingsJMenu.setText("Settings");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Hide imaginary components");
        settingsJMenu.add(jCheckBoxMenuItem1);

        jMenuBar1.add(settingsJMenu);

        helpJMenu.setText("Help");

        helpContentsJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        helpContentsJMenuItem.setText("Contents");
        helpContentsJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpContentsJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(helpContentsJMenuItem);
        helpJMenu.add(jSeparator1);

        aboutJMenuItem.setText("About");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        jMenuBar1.add(helpJMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addComponent(statusBarJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(leftJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBarJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpContentsJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpContentsJMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "help contents");
}//GEN-LAST:event_helpContentsJMenuItemActionPerformed

    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        AboutJDialog ajd = new AboutJDialog(this, true);
        ajd.setVisible(true);
}//GEN-LAST:event_aboutJMenuItemActionPerformed

    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJMenuItemActionPerformed
        /* TODO: Ask for confirmation */
        System.exit(0);
    }//GEN-LAST:event_quitJMenuItemActionPerformed

    private void newQuantumCircuitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newQuantumCircuitJMenuItemActionPerformed
        QCircuit qc = new QCircuit();
        qCircuitJPanel.setQcircuit(qc);
        qCircuitJPanel.repaint();
    }//GEN-LAST:event_newQuantumCircuitJMenuItemActionPerformed

    private void entanglementAlgorithmJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entanglementAlgorithmJMenuItemActionPerformed
        CompoundQGate s1 = new CompoundQGate(new ElementaryQGate[]{new Identity(),
                    new Hadamard(), new Identity()});
        CompoundQGate s2 = new CompoundQGate(
                new ElementaryQGate[]{new Identity(), new CNot()});
        CompoundQGate s3 = new CompoundQGate(new ElementaryQGate[]{new CNot(0, 1),
                    new Identity()});
        CompoundQGate s4 = new CompoundQGate(new ElementaryQGate[]{new CNot(0, 1),
                    new Identity()});

        QCircuit qcirc = new QCircuit(new CompoundQGate[]{s1, s2, s3, s4});
        qCircuitJPanel.setQcircuit(qcirc);
        writeMsg("Entangled states generation quantum circuit loaded");
        qCircuitJPanel.repaint();
    }//GEN-LAST:event_entanglementAlgorithmJMenuItemActionPerformed

    private void resetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJButtonActionPerformed
        qCircuitJPanel.setCurrentStage(0);
        qCircuitJPanel.repaint();
        writeMsg("Quantum state reset to initial value");
    }//GEN-LAST:event_resetJButtonActionPerformed

    private void stepJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepJButtonActionPerformed
        if (qCircuitJPanel.getCurrentStage() == qCircuitJPanel.getQcircuit().getStages().size()) {
            return;
        }
        qCircuitJPanel.setCurrentStage(qCircuitJPanel.getCurrentStage() + 1);
        qCircuitJPanel.repaint();
    }//GEN-LAST:event_stepJButtonActionPerformed

    public void writeMsg(String msg) {
        outputJTextArea.append(msg + "\n");
        statusBarJLabel.setText(msg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JMenu algorithmsJMenu;
    private javax.swing.JMenuItem entanglementAlgorithmJMenuItem;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JButton hadamardJButton;
    private javax.swing.JMenuItem helpContentsJMenuItem;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JMenuItem newQuantumCircuitJMenuItem;
    private javax.swing.JButton notJButton;
    private javax.swing.JTextArea outputJTextArea;
    private jqcompgui.QCircuitJPanel qCircuitJPanel;
    private javax.swing.JMenu quantumGatesJMenu;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JButton resetJButton;
    private javax.swing.JMenu settingsJMenu;
    private javax.swing.JLabel statusBarJLabel;
    private javax.swing.JPanel statusBarJPanel;
    private javax.swing.JButton stepJButton;
    // End of variables declaration//GEN-END:variables
}
