/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhaseShiftOptionsJPanel.java
 *
 * Created on 2008-12-25, 21:35:35
 */

package jqcompgui;

/**
 *
 * @author Andrzej
 */
public class PhaseShiftOptionsJPanel extends javax.swing.JPanel {

    /** Creates new form PhaseShiftOptionsJPanel */
    public PhaseShiftOptionsJPanel() {
        initComponents();
        angleNumericJTextField.setDef(Math.PI / 2);
    }

    public double getAngle() {
        if(radiansJCheckBox.isSelected()) {
            return angleNumericJTextField.getValue();
        } else {
            return angleNumericJTextField.getValue() * 180.0d / Math.PI;
        }
    }

    public void setAngle(double angle) {
        if(radiansJCheckBox.isSelected()) {
            angleNumericJTextField.setValue(angle);
        } else {
            angleNumericJTextField.setValue(angle * Math.PI / 180.0d);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        angleNumericJTextField = new jqcompgui.NumericJTextField();
        radiansJCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        angleNumericJTextField.setText("0.0");
        angleNumericJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angleNumericJTextFieldActionPerformed(evt);
            }
        });

        radiansJCheckBox.setSelected(true);
        radiansJCheckBox.setText("radians");
        radiansJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiansJCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Angle:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(angleNumericJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(radiansJCheckBox)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(angleNumericJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(radiansJCheckBox))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radiansJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiansJCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_radiansJCheckBoxActionPerformed

    private void angleNumericJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angleNumericJTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_angleNumericJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jqcompgui.NumericJTextField angleNumericJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox radiansJCheckBox;
    // End of variables declaration//GEN-END:variables

}
