/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhaseShiftOptionsJPanel.java
 *
 * Created on 2008-12-25, 21:35:35
 */

package jqcompgui;

/**
 *
 * @author Andrzej
 */
public class PhaseShiftOptionsJPanel extends javax.swing.JPanel {

    /** Creates new form PhaseShiftOptionsJPanel */
    public PhaseShiftOptionsJPanel() {
        initComponents();
        txtAngle.setDef(Math.PI / 2);
    }

    public double getAngle() {
        if(chkRadians.isSelected()) {
            return txtAngle.getValue();
        } else {
            return txtAngle.getValue() * 180.0d / Math.PI;
        }
    }

    public void setAngle(double angle) {
        if(chkRadians.isSelected()) {
            txtAngle.setValue(angle);
        } else {
            txtAngle.setValue(angle * Math.PI / 180.0d);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAngle = new jqcompgui.NumericJTextField();
        chkRadians = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        txtAngle.setText("0.0");

        chkRadians.setSelected(true);
        chkRadians.setText("radians");

        jLabel1.setText("Angle:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAngle, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chkRadians)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(txtAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(chkRadians))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkRadians;
    private javax.swing.JLabel jLabel1;
    private jqcompgui.NumericJTextField txtAngle;
    // End of variables declaration//GEN-END:variables

}
