/*
 * QCircuitJInternalFrame.java
 *
 * Created on 2008-12-15, 20:56:15
 */

package jqcompgui;

import pl.lodz.p.ics.quantum.jqcomp.QCircuit;
import pl.lodz.p.ics.quantum.jqcomp.qgates.Identity;
import java.util.EventObject;
import javax.swing.event.*;
import java.awt.event.*;


/**
 *
 * @author rob
 */
public class QCircuitJInternalFrame extends javax.swing.JInternalFrame {

    private int id;

    static private int lastId = 0;

    /** Creates new form QCircuitJInternalFrame */
    public QCircuitJInternalFrame() {
        this("Quantum Circuit");
    }

    public QCircuitJInternalFrame(String title) {
        initComponents();
        id = QCircuitJInternalFrame.lastId + 1;
        QCircuitJInternalFrame.lastId++;
        if (title == null || title.trim().equals("")) {
            title = "Quantum Circuit";
        }
        setTitle(String.format("(%1$s) %2$s",
                new Integer(id).toString(), title));

        getQCircuit().addStage(new Identity());

        monitor.stepChangedEvent().add(new Listener<EventObject>() {
            public void invoked(EventObject e) {
                getQCircuitJPanel().setCurrentStage(monitor.getCurrentStep());
            }
        });

        monitor.stateChangedEvent().add(new Listener<EventObject>() {
            public void invoked(EventObject e) {
                ExecutionMonitor m = (ExecutionMonitor)e.getSource();
                switch(m.getState()) {
                    case ExecutionMonitor.EXECUTED_STATE:
                        writeMsg("Executed\n  input: " + m.getCurrentInputRegister().dirac()
                               + "\n  output: " + m.getResultRegister().dirac());
                        break;

                    case ExecutionMonitor.STEP_EXECUTION_STATE:
                        writeMsg("Started step execution...");
                        break;

                    case ExecutionMonitor.INITIAL_STATE:
                        writeMsg("Quantum circuit state reset to initial value.");
                        break;

                    default:
                        assert(false);
                        break;
                }
            }
        });

        this.addInternalFrameListener(new InternalFrameAdapter() {
            public void internalFrameClosed(InternalFrameEvent e) {
                closeExecutionInfoJDialog();
            }
        });
    }

    public void showExecutionInfoJDialog(java.awt.Frame owner) {
        if(executionInfoJDialog == null) {
            executionInfoJDialog = new ExecutionInfoJDialog(owner, getExecutionMonitor());
            executionInfoJDialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            executionInfoJDialog.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {
                    executionInfoJDialog = null;
                }
            });
        }

        executionInfoJDialog.setVisible(true);
    }

    public void hideExecutionInfoJDialog() {
        closeExecutionInfoJDialog();
        //executionInfoJDialog.setVisible(false);
    }

    public boolean isExecutionInfoJDialogVisible() {
        if(executionInfoJDialog != null) {
            return executionInfoJDialog.isVisible();
        }

        return false;
    }

    public void closeExecutionInfoJDialog() {
        if(executionInfoJDialog != null) {
            executionInfoJDialog.setVisible(false);
            executionInfoJDialog.dispose();
            executionInfoJDialog = null;
        }
    }

    public void writeMsg(final String msg) {
        MainJFrame.getInstance().writeMsg(msg, getTitle());
    }

    private ExecutionInfoJDialog executionInfoJDialog = null;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        qCircuitJPanel = new jqcompgui.QCircuitJPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quantum Circuit");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout qCircuitJPanelLayout = new javax.swing.GroupLayout(qCircuitJPanel);
        qCircuitJPanel.setLayout(qCircuitJPanelLayout);
        qCircuitJPanelLayout.setHorizontalGroup(
            qCircuitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        qCircuitJPanelLayout.setVerticalGroup(
            qCircuitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(qCircuitJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the qcircuit
     */
    public QCircuit getQCircuit() {
        return qCircuitJPanel.getQCircuit();
    }

    /**
     * @param qcircuit the qcircuit to set
     */
    public void setQCircuit(QCircuit qcircuit) {
        qCircuitJPanel.setQCircuit(qcircuit);
        getExecutionMonitor().setQCircuit(qcircuit, getTitle());
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the qCircuitJPanel
     */
    public jqcompgui.QCircuitJPanel getQCircuitJPanel() {
        return qCircuitJPanel;
    }

    /**
     * @param qCircuitJPanel the qCircuitJPanel to set
     */
    public void setQCircuitJPanel(jqcompgui.QCircuitJPanel qCircuitJPanel) {
        this.qCircuitJPanel = qCircuitJPanel;
    }

    /**
     * @return the monitor
     */
    public ExecutionMonitor getExecutionMonitor() {
        return monitor;
    }

    private final ExecutionMonitor monitor = new ExecutionMonitor();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private jqcompgui.QCircuitJPanel qCircuitJPanel;
    // End of variables declaration//GEN-END:variables

   

}
