/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QCircuitJInternalFrame.java
 *
 * Created on 2008-12-15, 20:56:15
 */

package jqcompgui;

import pl.lodz.p.ics.quantum.jqcomp.QCircuit;

/**
 *
 * @author rob
 */
public class QCircuitJInternalFrame extends javax.swing.JInternalFrame {

    private int id;

    static private int lastId = 0;

    /** Creates new form QCircuitJInternalFrame */
    public QCircuitJInternalFrame() {
        this("Quantum Circuit");
    }

    public QCircuitJInternalFrame(String title) {
        initComponents();
        id = QCircuitJInternalFrame.lastId + 1;
        QCircuitJInternalFrame.lastId++;
        if (title == null || title.trim().equals("")) {
            title = "Quantum Circuit";
        }
        setTitle(String.format("(%1$s) %2$s",
                new Integer(id).toString(), title));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        qCircuitJPanel = new jqcompgui.QCircuitJPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quantum Circuit");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout qCircuitJPanelLayout = new javax.swing.GroupLayout(qCircuitJPanel);
        qCircuitJPanel.setLayout(qCircuitJPanelLayout);
        qCircuitJPanelLayout.setHorizontalGroup(
            qCircuitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        qCircuitJPanelLayout.setVerticalGroup(
            qCircuitJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(qCircuitJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the qcircuit
     */
    public QCircuit getQcircuit() {
        return qCircuitJPanel.getQcircuit();
    }

    /**
     * @param qcircuit the qcircuit to set
     */
    public void setQcircuit(QCircuit qcircuit) {
        qCircuitJPanel.setQcircuit(qcircuit);
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the qCircuitJPanel
     */
    public jqcompgui.QCircuitJPanel getQCircuitJPanel() {
        return qCircuitJPanel;
    }

    /**
     * @param qCircuitJPanel the qCircuitJPanel to set
     */
    public void setQCircuitJPanel(jqcompgui.QCircuitJPanel qCircuitJPanel) {
        this.qCircuitJPanel = qCircuitJPanel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private jqcompgui.QCircuitJPanel qCircuitJPanel;
    // End of variables declaration//GEN-END:variables

}
