/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QCircuitJPanel.java
 *
 * Created on 2008-12-04, 15:26:36
 */

package jqcompgui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author rob
 */
public class QCircuitJPanel extends javax.swing.JPanel {

    /** Creates new form QCircuitJPanel */
    public QCircuitJPanel() {
        initComponents(); 
    }

    @Override
    public void paintComponent(Graphics g1) {
        Graphics2D g = (Graphics2D) g1;
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());

        g.setColor(Color.BLACK);
        g.drawString("|0>", 30, 50);
        g.drawString("|0>", 30, 90);
        g.drawString("|0>", 30, 130);

        g.drawLine(60, 45, 150, 45);
        g.drawLine(60, 85, 150, 85);
        g.drawLine(60, 125, 150, 125);

        // ...

        /*
         * Draw quantum cicruit
         */

        /*
         * for (QStage s: qcircuit.stages) {
         *    ...
         * }
         */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
